version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ~/.gateward-dev/db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
networks: 
  postgres-network:
    driver: bridge
